# Sklearn

## sklearn.model_selection

документация: http://scikit-learn.org/stable/modules/cross_validation.html

In [30]:
from sklearn import model_selection, datasets

import numpy as np

### Разовое разбиение данных на обучение и тест с помощью train_test_split

In [31]:
iris = datasets.load_iris()

In [32]:
train_data, test_data, train_labels, test_labels = model_selection.train_test_split(iris.data, iris.target, 
                                                                                     test_size = 0.3)

In [33]:
#убедимся, что тестовая выборка действительно составляет 0.3 от всех данных
float(len(test_labels))/len(iris.data)

0.3

In [34]:
print 'Размер обучающей выборки: {} объектов \nРазмер тестовой выборки: {} объектов'.format(len(train_data),
                                                                                            len(test_data))

Размер обучающей выборки: 105 объектов 
Размер тестовой выборки: 45 объектов


In [35]:
print 'Обучающая выборка:\n', train_data[:5]
print '\n'
print 'Тестовая выборка:\n', test_data[:5]

Обучающая выборка:
[[ 4.9  3.1  1.5  0.1]
 [ 5.4  3.4  1.7  0.2]
 [ 5.9  3.   4.2  1.5]
 [ 5.5  3.5  1.3  0.2]
 [ 6.3  2.5  4.9  1.5]]


Тестовая выборка:
[[ 5.6  3.   4.1  1.3]
 [ 4.5  2.3  1.3  0.3]
 [ 6.   2.2  5.   1.5]
 [ 4.8  3.   1.4  0.3]
 [ 5.8  2.7  5.1  1.9]]


In [36]:
print 'Метки классов на обучающей выборке:\n', train_labels
print '\n'
print 'Метки классов на тестовой выборке:\n', test_labels

Метки классов на обучающей выборке:
[0 0 1 0 1 1 1 0 1 0 1 0 2 1 0 1 2 1 0 2 1 2 1 0 1 1 2 0 1 2 2 0 2 2 1 1 2
 1 2 2 1 2 2 0 0 1 0 1 0 1 0 0 2 2 2 0 0 1 1 2 1 2 0 0 0 1 2 1 0 2 2 0 2 2
 1 1 1 1 1 1 1 0 1 0 0 1 1 0 2 1 2 0 2 1 0 1 0 1 2 2 2 1 2 2 0]


Метки классов на тестовой выборке:
[1 0 2 0 2 2 0 1 1 1 2 0 0 0 1 2 0 0 0 2 2 2 2 2 2 1 2 0 0 1 0 1 0 0 1 2 2
 2 0 0 2 0 2 0 2]


### Стратегии проведения кросс-валидации

#### KFold

In [37]:
for train_indices, test_indices in model_selection.KFold(10, n_folds = 5):
    print train_indices, test_indices

TypeError: __init__() got an unexpected keyword argument 'n_folds'

In [ ]:
for train_indices, test_indices in model_selection.KFold(10, n_folds = 2, shuffle = True):
    print train_indices, test_indices

In [ ]:
for train_indices, test_indices in model_selection.KFold(10, n_folds = 2, shuffle = True, random_state = 1):
    print train_indices, test_indices

#### StratifiedKFold

In [ ]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in model_selection.StratifiedKFold(target, n_folds = 2, shuffle = True, random_state = 0):
    print train_indices, test_indices

In [ ]:
target = np.array([0, 1] * 5)
print target
for train_indices, test_indices in model_selection.StratifiedKFold(target, n_folds = 2,shuffle = True):
    print train_indices, test_indices

#### ShuffleSplit

In [ ]:
for train_indices, test_indices in model_selection.ShuffleSplit(10, n_iter = 10, test_size = 0.2):
    print train_indices, test_indices

#### StratifiedShuffleSplit

In [ ]:
target = np.array([0] * 5 + [1] * 5)
print target
for train_indices, test_indices in model_selection.StratifiedShuffleSplit(target, n_iter = 4, test_size = 0.2):
    print train_indices, test_indices

#### Leave-One-Out

In [ ]:
for train_indices, test_index in model_selection.LeaveOneOut(10):
    print train_indices, test_index

Больше стратегий проведения кросс-валидации доступно здесь: http://scikit-learn.org/stable/modules/cross_validation.html#cross-validation-iterators